# This file may be used to create a conda environment using:
# $ conda create --name gprMax --file <this file>

name: gprMax
dependencies:
  - python=3.7.*
  - colorama=0.4.*
  - cython=0.29.*
  - h5py=3.3.*
  - jupyter=1.0.*
  - matplotlib=3.4.*
  - numpy=1.19.*
  - pandas=1.3.*
  - pip=21.3.*
  - psutil=5.8.*
  - pytest=6.2.*
  - scipy=1.7.*

  - pip:
    - terminaltables==3.1.*
    - tqdm==4.61.*
    # - mpi4py
    # - pycuda

